/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsUtilsRouteImport } from './routes/tools.utils'
import { Route as ToolsPayloadsRouteImport } from './routes/tools.payloads'
import { Route as ToolsEncoderRouteImport } from './routes/tools.encoder'
import { Route as SecurityGrabRouteImport } from './routes/security.grab'
import { Route as SecurityEzxssRouteImport } from './routes/security.ezxss'
import { Route as SecurityEventsRouteImport } from './routes/security.events'
import { Route as SecurityDnsRouteImport } from './routes/security.dns'
import { Route as AuthSilentCallbackRouteImport } from './routes/auth.silent-callback'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUtilsRoute = ToolsUtilsRouteImport.update({
  id: '/tools/utils',
  path: '/tools/utils',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPayloadsRoute = ToolsPayloadsRouteImport.update({
  id: '/tools/payloads',
  path: '/tools/payloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsEncoderRoute = ToolsEncoderRouteImport.update({
  id: '/tools/encoder',
  path: '/tools/encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityGrabRoute = SecurityGrabRouteImport.update({
  id: '/security/grab',
  path: '/security/grab',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityEzxssRoute = SecurityEzxssRouteImport.update({
  id: '/security/ezxss',
  path: '/security/ezxss',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityEventsRoute = SecurityEventsRouteImport.update({
  id: '/security/events',
  path: '/security/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityDnsRoute = SecurityDnsRouteImport.update({
  id: '/security/dns',
  path: '/security/dns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSilentCallbackRoute = AuthSilentCallbackRouteImport.update({
  id: '/auth/silent-callback',
  path: '/auth/silent-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/programs': typeof ProgramsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/security/dns': typeof SecurityDnsRoute
  '/security/events': typeof SecurityEventsRoute
  '/security/ezxss': typeof SecurityEzxssRoute
  '/security/grab': typeof SecurityGrabRoute
  '/tools/encoder': typeof ToolsEncoderRoute
  '/tools/payloads': typeof ToolsPayloadsRoute
  '/tools/utils': typeof ToolsUtilsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/programs': typeof ProgramsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/security/dns': typeof SecurityDnsRoute
  '/security/events': typeof SecurityEventsRoute
  '/security/ezxss': typeof SecurityEzxssRoute
  '/security/grab': typeof SecurityGrabRoute
  '/tools/encoder': typeof ToolsEncoderRoute
  '/tools/payloads': typeof ToolsPayloadsRoute
  '/tools/utils': typeof ToolsUtilsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/programs': typeof ProgramsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/security/dns': typeof SecurityDnsRoute
  '/security/events': typeof SecurityEventsRoute
  '/security/ezxss': typeof SecurityEzxssRoute
  '/security/grab': typeof SecurityGrabRoute
  '/tools/encoder': typeof ToolsEncoderRoute
  '/tools/payloads': typeof ToolsPayloadsRoute
  '/tools/utils': typeof ToolsUtilsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/programs'
    | '/settings'
    | '/auth/callback'
    | '/auth/silent-callback'
    | '/security/dns'
    | '/security/events'
    | '/security/ezxss'
    | '/security/grab'
    | '/tools/encoder'
    | '/tools/payloads'
    | '/tools/utils'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/programs'
    | '/settings'
    | '/auth/callback'
    | '/auth/silent-callback'
    | '/security/dns'
    | '/security/events'
    | '/security/ezxss'
    | '/security/grab'
    | '/tools/encoder'
    | '/tools/payloads'
    | '/tools/utils'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/programs'
    | '/settings'
    | '/auth/callback'
    | '/auth/silent-callback'
    | '/security/dns'
    | '/security/events'
    | '/security/ezxss'
    | '/security/grab'
    | '/tools/encoder'
    | '/tools/payloads'
    | '/tools/utils'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  ProgramsRoute: typeof ProgramsRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSilentCallbackRoute: typeof AuthSilentCallbackRoute
  SecurityDnsRoute: typeof SecurityDnsRoute
  SecurityEventsRoute: typeof SecurityEventsRoute
  SecurityEzxssRoute: typeof SecurityEzxssRoute
  SecurityGrabRoute: typeof SecurityGrabRoute
  ToolsEncoderRoute: typeof ToolsEncoderRoute
  ToolsPayloadsRoute: typeof ToolsPayloadsRoute
  ToolsUtilsRoute: typeof ToolsUtilsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/utils': {
      id: '/tools/utils'
      path: '/tools/utils'
      fullPath: '/tools/utils'
      preLoaderRoute: typeof ToolsUtilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/payloads': {
      id: '/tools/payloads'
      path: '/tools/payloads'
      fullPath: '/tools/payloads'
      preLoaderRoute: typeof ToolsPayloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/encoder': {
      id: '/tools/encoder'
      path: '/tools/encoder'
      fullPath: '/tools/encoder'
      preLoaderRoute: typeof ToolsEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/grab': {
      id: '/security/grab'
      path: '/security/grab'
      fullPath: '/security/grab'
      preLoaderRoute: typeof SecurityGrabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/ezxss': {
      id: '/security/ezxss'
      path: '/security/ezxss'
      fullPath: '/security/ezxss'
      preLoaderRoute: typeof SecurityEzxssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/events': {
      id: '/security/events'
      path: '/security/events'
      fullPath: '/security/events'
      preLoaderRoute: typeof SecurityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/dns': {
      id: '/security/dns'
      path: '/security/dns'
      fullPath: '/security/dns'
      preLoaderRoute: typeof SecurityDnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/silent-callback': {
      id: '/auth/silent-callback'
      path: '/auth/silent-callback'
      fullPath: '/auth/silent-callback'
      preLoaderRoute: typeof AuthSilentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  ProgramsRoute: ProgramsRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSilentCallbackRoute: AuthSilentCallbackRoute,
  SecurityDnsRoute: SecurityDnsRoute,
  SecurityEventsRoute: SecurityEventsRoute,
  SecurityEzxssRoute: SecurityEzxssRoute,
  SecurityGrabRoute: SecurityGrabRoute,
  ToolsEncoderRoute: ToolsEncoderRoute,
  ToolsPayloadsRoute: ToolsPayloadsRoute,
  ToolsUtilsRoute: ToolsUtilsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
